### ISSUE TITLE
Bug in Selenium Chrome Driver

### ISSUE THREAD

**Issue by winb1g** [quinctilis/ism-scores#2]
When using the program, I get the following response in the console:
`There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
Could not read url {{redacted}}`

**Comment by quinctilis** [comment]
Thanks for pointing out!. Turns out that there is no need to manually install the driver as suggested [here](https://stackoverflow.com/questions/76724939/there-is-no-such-driver-by-url-https-chromedriver-storage-googleapis-com-lates)
Usually this happens after upgrading chrome. Also happened in my machine.
Should be resolved here #3 
Note that I also bumped the driver version so we don't see legacy warnings.

**Comment by winb1g** [comment]
Thanks for your great work
